name: Trigger Another Project Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Run testing
      run: |
          echo "Running tests"
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: jdmesalosada
        repo: react-course
        github_token: ${{ secrets.PAT_TOKEN }}
        workflow_file_name: testing-flow.yaml          