name: React course

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'serenity-rest-archetype'
        required: true
      branch:
        description: 'main'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run testing
      env:
        REPO_NAME: ${{ github.event.inputs.repository_name }}
        BRANCH: ${{ github.event.inputs.branch }}
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/${REPO_NAME}/actions/workflows/testing-flow.yaml/dispatches" \
        -d '{"ref": "${BRANCH}"}'